import { useQuery, useMutation, useQueryClient, type UseQueryOptions, type UseMutationOptions } from '@tanstack/react-query';
import {
  settlementApi,
  settlementRailService,
  type CreateRailData,
  type UpdateRailData,
  type SelectBestRailParams,
  type SettlementRailsFilterParams,
} from '@services';
import type { SettlementRail, RailTransaction, RailStats } from '@types';
import { PaginatedResponse } from '@/types';
import { createResourceHooks } from '@/hooks/createResourceHooks';

export type { SettlementRailsFilterParams };

/**
 * Create all settlement rail CRUD hooks using the generic factory.
 * Covers detail, create, update (PUT), patch, delete, and bulk-delete operations.
 */
const settlementRailHooks = createResourceHooks<SettlementRail>('settlement-rails', settlementRailService);

/**
 * Query keys for settlement rails - use for manual cache invalidation.
 *
 * Note: The factory key namespace is `settlement-rails`. Legacy keys below
 * (e.g. `settlementKeys.rails()`) continue to work for custom hooks that
 * use domain-specific endpoints not covered by the factory.
 */
export const settlementRailKeys = settlementRailHooks.keys;

/**
 * Legacy key helpers kept for custom hooks that reference domain-specific endpoints.
 */
export const settlementKeys = {
  all: ['settlement'] as const,
  rails: () => [...settlementKeys.all, 'rails'] as const,
  railsFiltered: (params?: SettlementRailsFilterParams) => [...settlementKeys.rails(), 'filtered', params] as const,
  rail: (id: string) => [...settlementKeys.all, 'rail', id] as const,
  transactions: (railId: string) => [...settlementKeys.all, 'transactions', railId] as const,
  stats: (railId: string) => [...settlementKeys.all, 'stats', railId] as const,
};

// ---------------------------------------------------------------------------
// CRUD hooks — generated by factory
// ---------------------------------------------------------------------------

/**
 * Hook to fetch a single settlement rail by ID.
 *
 * @example
 * ```tsx
 * const { data: rail, isLoading } = useSettlementRail('rail-123');
 * ```
 */
export const useSettlementRail = settlementRailHooks.useDetail;

/**
 * Hook to create a new settlement rail.
 *
 * @example
 * ```tsx
 * const createRail = useCreateRail();
 * createRail.mutate({ name: 'NCHL', provider: 'NCHL', ... });
 * ```
 */
export const useCreateRail = settlementRailHooks.useCreate;

/**
 * Hook to perform a full update of a settlement rail (PUT).
 *
 * @example
 * ```tsx
 * const updateRail = useUpdateRail();
 * updateRail.mutate({ id: 'rail-123', data: { status: 'DOWN' } });
 * ```
 */
export const useUpdateRail = settlementRailHooks.useUpdate;

/**
 * Hook to perform a partial update of a settlement rail (PATCH).
 *
 * @example
 * ```tsx
 * const patchRail = usePatchRail();
 * patchRail.mutate({ id: 'rail-123', data: { priority: 2 } });
 * ```
 */
export const usePatchRail = settlementRailHooks.usePatch;

/**
 * Hook to delete a settlement rail.
 *
 * @example
 * ```tsx
 * const deleteRail = useDeleteRail();
 * deleteRail.mutate('rail-123');
 * ```
 */
export const useDeleteRail = settlementRailHooks.useDelete;

/**
 * Hook to delete multiple settlement rails at once.
 *
 * @example
 * ```tsx
 * const bulkDelete = useBulkDeleteRails();
 * bulkDelete.mutate(['rail-1', 'rail-2']);
 * ```
 */
export const useBulkDeleteRails = settlementRailHooks.useBulkDelete;

// ---------------------------------------------------------------------------
// Custom hooks — kept verbatim (domain-specific endpoints not covered by factory)
// ---------------------------------------------------------------------------

/**
 * Hook to fetch all settlement rails (returns plain array, not paginated).
 */
export function useSettlementRails(
  options?: Omit<UseQueryOptions<SettlementRail[]>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: settlementKeys.rails(),
    queryFn: () => settlementApi.getAllRails(),
    ...options,
  });
}

/**
 * Hook to fetch filtered settlement rails with pagination and search.
 */
export function useFilteredSettlementRails(
  params?: SettlementRailsFilterParams,
  options?: Omit<UseQueryOptions<PaginatedResponse<SettlementRail>>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: settlementKeys.railsFiltered(params),
    queryFn: () => settlementApi.getFilteredRails(params || {}),
    ...options,
  });
}

/**
 * Hook to fetch transactions for a rail.
 */
export function useRailTransactions(
  railId: string,
  options?: Omit<UseQueryOptions<RailTransaction[]>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: settlementKeys.transactions(railId),
    queryFn: () => settlementApi.getRailTransactions(railId),
    enabled: !!railId,
    ...options,
  });
}

/**
 * Hook to fetch rail statistics.
 */
export function useRailStats(
  railId: string,
  options?: Omit<UseQueryOptions<RailStats>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: settlementKeys.stats(railId),
    queryFn: () => settlementApi.getRailStats(railId),
    enabled: !!railId,
    ...options,
  });
}

/**
 * Hook to select best rail for payment.
 * This doesn't cache as it's usually used for real-time decisions.
 */
export function useSelectBestRail(
  params: SelectBestRailParams,
  options?: Omit<UseQueryOptions<SettlementRail>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: [...settlementKeys.all, 'select-best', params],
    queryFn: () => settlementApi.selectBestRail(params),
    enabled: !!params.amount,
    staleTime: 0, // Always fresh
    ...options,
  });
}

/**
 * Hook to health check a rail.
 */
export function useHealthCheckRail(
  options?: Omit<UseMutationOptions<{ status: string; latencyMs: number }, Error, string>, 'mutationFn'>
) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (railId: string) => settlementApi.healthCheck(railId),
    onSuccess: (_, railId) => {
      queryClient.invalidateQueries({ queryKey: settlementKeys.rail(railId) });
      queryClient.invalidateQueries({ queryKey: settlementKeys.rails() });
    },
    ...options,
  });
}

/**
 * Hook to fetch active bank providers (settlement rails) for dropdown selection.
 * Used in supplier onboarding to let users select their preferred bank/payment provider.
 */
export function useActiveBankProviders(
  options?: Omit<UseQueryOptions<SettlementRail[]>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: [...settlementKeys.all, 'active-providers'],
    queryFn: async () => {
      const result = await settlementApi.getActiveRails();
      // Handle both direct array and paginated response
      if (Array.isArray(result)) {
        return result;
      }
      const paginatedResult = result as PaginatedResponse<SettlementRail>;
      return paginatedResult.items || [];
    },
    staleTime: 10 * 60 * 1000, // 10 minutes
    ...options,
  });
}
