import { useQuery, useMutation, useQueryClient, type UseQueryOptions, type UseMutationOptions } from '@tanstack/react-query';
import { userApi, type UpdateUserSettingsData } from '@services';
import { createResourceHooks } from '@/hooks/createResourceHooks';
import { userService } from '@/lib/apiService';
import type { User, UserSettings } from '@types';
import type { PaginatedResponse } from '@types';

export interface UserListParams extends Record<string, unknown> {
  page?: number;
  pageSize?: number;
  search?: string;
  role?: string;
  isActive?: boolean;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

/**
 * Create all user-related React Query hooks using the generic factory
 *
 * Standard CRUD hooks (useList, useDetail, useCreate, usePatch, useDelete, useBulkDelete)
 * are generated by the factory. Custom hooks (useMe, useUserSettings,
 * useUpdateUserSettings, useUpdateUser, useUploadAvatar) are kept below.
 */
const userCrud = createResourceHooks<User>('users', userService);

/**
 * Query keys for users — use for manual cache invalidation.
 * Extended with user-specific keys (me, settings) below.
 */
export const userKeys = {
  ...userCrud.keys,
  me: () => ['users', 'me'] as const,
  settings: (id: string) => ['users', 'settings', id] as const,
};

/**
 * Hook to fetch paginated list of users
 */
export const useUsers = (
  params?: UserListParams,
  options?: Omit<UseQueryOptions<PaginatedResponse<User>>, 'queryKey' | 'queryFn'>
) => userCrud.useList(params, options);

/**
 * Hook to fetch single user by ID
 */
export const useUser = userCrud.useDetail;

/**
 * Hook to create a new user
 */
export const useCreateUser = userCrud.useCreate;

/**
 * Hook to perform partial update of a user (PATCH)
 * For a full update that also invalidates the /me cache, use useUpdateUser.
 */
export const usePatchUser = userCrud.usePatch;

/**
 * Hook to delete a user
 */
export const useDeleteUser = userCrud.useDelete;

/**
 * Hook to bulk-delete users
 */
export const useBulkDeleteUsers = userCrud.useBulkDelete;

// ---------------------------------------------------------------------------
// Custom hooks — kept verbatim from original implementation
// ---------------------------------------------------------------------------

/**
 * Hook to fetch current authenticated user profile from API
 *
 * This is the RECOMMENDED way to get current user data in the application.
 * It fetches fresh data from /users/me endpoint and caches it via React Query.
 *
 * @example
 * ```tsx
 * function UserProfile() {
 *   const { data: user, isLoading, error, refetch } = useMe();
 *
 *   if (isLoading) return <div>Loading...</div>;
 *   if (error) return <div>Error: {error.message} <button onClick={() => refetch()}>Retry</button></div>;
 *
 *   return <div>Hello, {user.username}!</div>;
 * }
 * ```
 */
export function useMe(
  options?: Omit<UseQueryOptions<User>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: userKeys.me(),
    queryFn: () => userApi.me(),
    staleTime: 5 * 60 * 1000,
    gcTime: 10 * 60 * 1000,
    refetchOnMount: false,
    refetchOnWindowFocus: false,
    ...options,
  });
}

/**
 * Hook to fetch user settings
 */
export function useUserSettings(
  userId: string,
  options?: Omit<UseQueryOptions<UserSettings>, 'queryKey' | 'queryFn'>
) {
  return useQuery({
    queryKey: userKeys.settings(userId),
    queryFn: () => userApi.getUserSettings(userId),
    enabled: !!userId,
    ...options,
  });
}

/**
 * Hook to update user — also invalidates /me cache when the updated user
 * is the currently authenticated user.
 */
export function useUpdateUser(
  options?: Omit<UseMutationOptions<User, Error, { id: string; data: Parameters<typeof userApi.update>[1] }>, 'mutationFn'>
) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: Parameters<typeof userApi.update>[1] }) => userApi.update(id, data),
    onSuccess: (updatedUser) => {
      queryClient.invalidateQueries({ queryKey: userKeys.detail(updatedUser.id) });
      queryClient.invalidateQueries({ queryKey: userKeys.lists() });

      const currentUser = queryClient.getQueryData<User>(userKeys.me());
      if (currentUser && currentUser.id === updatedUser.id) {
        queryClient.invalidateQueries({ queryKey: userKeys.me() });
      }
    },
    ...options,
  });
}

/**
 * Hook to update user settings
 */
export function useUpdateUserSettings(
  options?: Omit<UseMutationOptions<UserSettings, Error, { userId: string; data: UpdateUserSettingsData }>, 'mutationFn'>
) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ userId, data }: { userId: string; data: UpdateUserSettingsData }) =>
      userApi.updateSettings(userId, data),
    onSuccess: (_, { userId }) => {
      queryClient.invalidateQueries({ queryKey: userKeys.settings(userId) });
    },
    ...options,
  });
}

/**
 * Hook to upload user avatar
 */
export function useUploadAvatar(
  options?: Omit<UseMutationOptions<User, Error, { userId: string; file: File }>, 'mutationFn'>
) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ userId, file }: { userId: string; file: File }) => userApi.uploadAvatar(userId, file),
    onSuccess: (_, { userId }) => {
      queryClient.invalidateQueries({ queryKey: userKeys.detail(userId) });
      queryClient.invalidateQueries({ queryKey: userKeys.me() });
    },
    ...options,
  });
}
