import { useQuery, useMutation, useQueryClient, type UseQueryOptions, type UseMutationOptions } from '@tanstack/react-query';
import { createResourceHooks } from '@/hooks/createResourceHooks';
import { apiKeyService } from '@/features/developer/services/apiKeyApi';
import { apiKeyApi } from '@/features/developer/services/apiKeyApi';
import type { ApiKey } from '@types';

/**
 * Standard CRUD hooks generated by createResourceHooks factory.
 * Provides useList, useDetail, useCreate, useUpdate, usePatch, useDelete, useBulkDelete.
 */
const apiKeyHooks = createResourceHooks<ApiKey>('apiKeys', apiKeyService);

/**
 * Query keys for API keys - use for manual cache invalidation
 */
export const apiKeyKeys = apiKeyHooks.keys;

/**
 * Hook to fetch paginated list of API keys
 */
export const useApiKeys = apiKeyHooks.useList;

/**
 * Hook to fetch a single API key by ID
 */
export const useApiKey = apiKeyHooks.useDetail;

/**
 * Hook to create a new API key
 */
export const useCreateApiKey = apiKeyHooks.useCreate;

/**
 * Hook to perform full update of an API key (PUT)
 */
export const useUpdateApiKey = apiKeyHooks.useUpdate;

/**
 * Hook to perform partial update of an API key (PATCH)
 */
export const usePatchApiKey = apiKeyHooks.usePatch;

/**
 * Hook to delete an API key
 */
export const useDeleteApiKey = apiKeyHooks.useDelete;

/**
 * Hook to delete multiple API keys at once
 */
export const useBulkDeleteApiKeys = apiKeyHooks.useBulkDelete;

/**
 * Hook to revoke an API key (custom — uses dedicated revoke endpoint)
 * Invalidates both the specific key detail and the list cache.
 */
export function useRevokeApiKey(
  options?: Omit<UseMutationOptions<void, Error, string>, 'mutationFn'>
) {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: string) => apiKeyApi.revoke(id),
    onSuccess: (_, id) => {
      queryClient.invalidateQueries({ queryKey: apiKeyKeys.detail(id) });
      queryClient.invalidateQueries({ queryKey: apiKeyKeys.lists() });
    },
    ...options,
  });
}
